- set_fact:
    _service_path: "{{ fiware.delivery_robot.service_path }}"
    _temp_file: cygnus_mongo_subscriber_robot_device.json.j2

- include_tasks: check_subscriber.yml

- include_tasks: delete_subscriber.yml
  with_items: "{{ check_subscriber_result.json }}"
  loop_control:
    loop_var: subscriber
  when: check_subscriber_result.json | length | int > 0

- include_tasks: register_subscriber.yml
  loop: "{{ subscriptions.delibery_robot }}"
  loop_control:
    loop_var: _attrs
